/* أنا منو؟ — بطاقات المهن
   لكل بطاقة: slug (اسم ملف الصورة داخل cards/ بصيغة png أو jpg أو webp)، الاسم، لون الخلفية، رمز بديل، وتلميحات.
   لإضافة بطاقة جديدة: أضِف سطرًا هنا وضع صورتها في cards/<slug>.png — أو أضِف الصورة من داخل اللعبة (🖼️ صور البطاقات). */
window.ANAMENU_CARDS = [
  { slug:'doctor-m',        name:'طبيب',            bg:'#2FA8E6', emoji:'🧑‍⚕️', hint:'يعالج المرضى ويكتب الدواء' },
  { slug:'doctor-f',        name:'طبيبة',           bg:'#2CC9A8', emoji:'👩‍⚕️', hint:'تعالج المرضى وتستمع لنبض القلب' },
  { slug:'engineer-m',      name:'مهندس',           bg:'#F7C61F', emoji:'👷',   hint:'خوذة صفراء ومخططات زرقاء' },
  { slug:'engineer-f',      name:'مهندسة',          bg:'#F04B3B', emoji:'👷‍♀️', hint:'خوذة بيضاء وجهاز لوحي في الموقع' },
  { slug:'chef-m',          name:'طباخ',            bg:'#F04B3B', emoji:'👨‍🍳', hint:'قبعة بيضاء وملعقة خشبية' },
  { slug:'chef-f',          name:'طباخة',           bg:'#6B3FC9', emoji:'👩‍🍳', hint:'تُعدّ ألذّ الأطباق في المطبخ' },
  { slug:'pilot-m',         name:'طيار',            bg:'#1E7FE0', emoji:'👨‍✈️', hint:'يقود الطائرة فوق الغيوم' },
  { slug:'pilot-f',         name:'طيارة',           bg:'#38B6E8', emoji:'👩‍✈️', hint:'قبعة كحلية وأجنحة ذهبية' },
  { slug:'programmer-m',    name:'مبرمج',           bg:'#2CC9A8', emoji:'👨‍💻', hint:'يكتب الأكواد على الحاسوب' },
  { slug:'programmer-f',    name:'مبرمجة',          bg:'#F7C61F', emoji:'👩‍💻', hint:'تصنع التطبيقات والمواقع' },
  { slug:'photographer-m',  name:'مصور',            bg:'#6B3FC9', emoji:'📷',   hint:'يحمل الكاميرا ويلتقط الصور' },
  { slug:'photographer-f',  name:'مصورة',           bg:'#2CC9A8', emoji:'📸',   hint:'قبعة قش وكاميرا احترافية' },
  { slug:'teacher-m',       name:'معلم',            bg:'#2FA8E6', emoji:'👨‍🏫', hint:'يحمل كتابًا ويشرح الدرس' },
  { slug:'teacher-f',       name:'معلمة',           bg:'#F04B3B', emoji:'👩‍🏫', hint:'تشرح الدرس على السبورة' },
  { slug:'police-m',        name:'شرطي',            bg:'#1E7FE0', emoji:'👮',   hint:'زيّ كحلي ونجمة ذهبية' },
  { slug:'police-f',        name:'شرطية',           bg:'#6B3FC9', emoji:'👮‍♀️', hint:'تحفظ الأمن وتنظّم المرور' },
  { slug:'firefighter-m',   name:'رجل إطفاء',       bg:'#F04B3B', emoji:'👨‍🚒', hint:'خوذة حمراء ويطفئ الحرائق' },
  { slug:'architect-f',     name:'مهندسة معمارية',  bg:'#F7C61F', emoji:'📐',   hint:'تصمّم المباني وترسم المخططات' },
  { slug:'farmer-m',        name:'مزارع',           bg:'#2CC9A8', emoji:'👨‍🌾', hint:'قبعة قش وسنابل قمح' },
  { slug:'farmer-f',        name:'مزارعة',          bg:'#F7C61F', emoji:'👩‍🌾', hint:'تزرع الأرض وتحصد القمح' },
  { slug:'graphic-designer-m', name:'مصمم جرافيك', bg:'#F04B3B', emoji:'🎨',   hint:'يرسم التصاميم على الجهاز اللوحي' },
  { slug:'fashion-designer-f', name:'مصممة أزياء', bg:'#6B3FC9', emoji:'👗',   hint:'شريط قياس وتصمّم الملابس' },
  { slug:'dentist-m',       name:'طبيب أسنان',      bg:'#2FA8E6', emoji:'🦷',   hint:'مرآة صغيرة ويفحص الأسنان' },
  { slug:'pharmacist-f',    name:'صيدلانية',        bg:'#2CC9A8', emoji:'💊',   hint:'تصرف الدواء في الصيدلية' },
  { slug:'electrician-m',   name:'كهربائي',         bg:'#F7C61F', emoji:'💡',   hint:'خوذة برتقالية ومصباح مضيء' },
  { slug:'mechanic-f',      name:'ميكانيكية',       bg:'#1E7FE0', emoji:'🔧',   hint:'مفتاح ربط وتصلح السيارات' },
  { slug:'lawyer-m',        name:'محامي',           bg:'#6B3FC9', emoji:'⚖️',   hint:'ميزان العدالة وبدلة رسمية' },
  { slug:'journalist-f',    name:'صحفية',           bg:'#F04B3B', emoji:'🎤',   hint:'تحمل الميكروفون وتنقل الأخبار' },
  { slug:'baker-m',         name:'خباز',            bg:'#F7C61F', emoji:'🍞',   hint:'يخبز الخبز الطازج كل صباح' },
  { slug:'business-manager-f', name:'مديرة أعمال', bg:'#2FA8E6', emoji:'💼',   hint:'حقيبة جلدية وتدير الشركة' },
];
